@startuml
'https://plantuml.com/class-diagram

class Solution42 {
+main(args String)
- in main:
create class variable
print header
print line spacer
call output method
+printOutput(String filename)
- in printOutput:
declare file and scanner
scan input file while there's a next name
throw exception if no file
}



@enduml