@startuml
'https://plantuml.com/class-diagram


class Solution43 {
+inputMethod(prompt: String)
- in inputMethod:
print prompt
return next String

+main(args: String)
- in main:
prompt for website name
prompt for author
make new directory "website"
    prompt for javascript folder
    prompt for css folder
    if yes for either make sub directories for the
}
@enduml